# $FreeBSD$

PORTNAME=	typetod
PORTVERSION= 0.02
PORTREVISION=	1
CATEGORIES=	games
MASTER_SITES=	http://github.com/raviqqe/${PORTNAME}/raw/master/pkg/

MAINTAINER=	raviqqe@gmail.com
COMMENT= typing game with endless mode

LICENSE= public
LICENSE_NAME= Public Domain
LICENSE_FILE=	${WRKSRC}/UNLICENSE
LICENSE_PERMS=  dist-mirror dist-sell pkg-mirror pkg-sell auto-accept

RUN_DEPENDS= python3:${PORTBASE}/lang/python3

#.include <bsd.port.options.mk>
.include <bsd.port.mk>
