.TH TYPETOD 6 typetod\-VERSION
.SH NAME
typetod \- typing game with endless mode
.SH SYNOPSIS
typetod [\-a <attribute>] [\-c] [\-d] [\-e] [\-f] [\-l <character>] [\-m] [\-n]
[\-q] [\-r] [\-s] [\-t <integer>] [\-w]
.SH DESCRIPTION
typetod is a typing game which has four modes; fortune mode (default), files
mode, RSS feeds mode, and stdin mode. And, with the first three modes, you can
play with its endless mode. You can exit a game or leave from the screen
anywhere typing an escape key or ctrl + e. On the menu screen, you can move
downwards typing j and upwards typing k, and play a game with the content of
the selected title typing space or enter key.
.TP
.I
fortune mode
Benefitial tips from fortune command as samples.
.TP
.I
files mode
Text files which are local or remote (passed as URLs with http or ftp scheme)
as samples.
.TP
.I
RSS feeds mode
the artilcles in a RSS feed as samples.
.TP
.I
stdin mode
In this mode, typetod reads lines one by one from stdin adding it to the
buffer of samples during the game. To enable this mode, use pipes on the
command line.
.SH OPTIONS
.TP
.B \-a <attribute>
sets the attribute of characters which is mistyped. Valid arguments are
\'reverse\' (default), \'blink\', \'bold\', \'underline\', and \'normal\'.
.TP
.B \-c
changes the unit of typing speed to cps. The default is wpm.
.TP
.B \-d
enables endless mode which is valid only with fortune mode, files mode, and RSS
feeds mode.
.TP
.B \-e
removes empty lines from your sample texts. It should remove all of them that
can be generated by not only sample texts, but typetod itself to distinguish
each of them from the others.
.TP
.B \-f
switches the game mode to RSS feeds mode. You also specify one url to the RSS
feed as the command argument.
.TP
.B \-l <character>
sets the character used to draw two lines right next to the input line.
.TP
.B \-m
toggle display of menu screen.
.TP
.B \-n
enables the feature of morphing text. This can be removed in the next version
when it seems to be not popular.
.TP
.B \-q
makes it quiet without any result screen and status bar.
.TP
.B \-r
enable you to specify directories as arguments on files mode. typetod will
search the directories to find files in them by one level.
.TP
.B \-s
disable the status bar.
.TP
.B \-t
set the number of spaces per tab. typetod always converts all tabs of samples
and input characters into spaces.
.TP
.B \-w
convert multiple space to one space and erase spaces at the beginnning of the
line.
.SH NOTES
This program depends on the
.I feedparser
package of python.
.SH EXAMPLE
.TP
typetod
executes typetod in fortune mode.
.TP
typetod -d
executes typetod in endless fortune mode.
.TP
typetod some_text_file another_text_file
executes typetod in files mode.
.TP
typetod -f http://www.autocar.co.uk/rss/
executes typetod in RSS feeds mode. This is not a advertisement cause I loves
cars.
.TP
fortune | typetod
one-time fortune mode by stdin mode
.SH SEE ALSO
.I python
